# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fingerprint_pb2 as fingerprint__pb2


class FingerprinterStub(object):
    """The fingerprint generation service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateOne = channel.unary_unary(
                '/fingerprint.Fingerprinter/GenerateOne',
                request_serializer=fingerprint__pb2.PrintRequest.SerializeToString,
                response_deserializer=fingerprint__pb2.Fingerprint.FromString,
                )


class FingerprinterServicer(object):
    """The fingerprint generation service definition.
    """

    def GenerateOne(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FingerprinterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateOne,
                    request_deserializer=fingerprint__pb2.PrintRequest.FromString,
                    response_serializer=fingerprint__pb2.Fingerprint.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fingerprint.Fingerprinter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Fingerprinter(object):
    """The fingerprint generation service definition.
    """

    @staticmethod
    def GenerateOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fingerprint.Fingerprinter/GenerateOne',
            fingerprint__pb2.PrintRequest.SerializeToString,
            fingerprint__pb2.Fingerprint.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
